Repository Adversarial-Deep-Learning/code-soup, pull requests merged in 2021-08, with the labels that each got.

#4 Integrate CI
  .github/workflows/python-package.yml
  .gitignore
  tests/test_cv5/test_empty.py
Labels: Implementation, Priority:High

#5 Codecov Action Added
  .github/workflows/codecov-workflow.yml
  codecov.yml
  requirements.txt
Labels: Implementation

#27 Add Doc Strings
  code_soup/ch5/datasets/mnist.py
  code_soup/ch5/models/gan.py
Labels: documentation

#32 Documentation Fix
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#33 Add Repository Structure
  README.md
  REPO_STRUCTURE.md
Labels: documentation

#42 Add ZOO Attack
  code_soup/ch5/models/configs/zoo_attack.json
  code_soup/ch5/models/zoo_attack.py
  code_soup/common/utils.py
  code_soup/common/vision/models/simple_cnn_classifier.py
  requirements.txt
  tests/test_ch5/test_models/test_zoo_attack.py
  tests/test_common/test_utils.py
  tests/test_common/test_vision/test_models/test_simple_cnn_classifier.py
Labels: Priority:High, Algorithm, Implementation
